default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flash_cards_development

test:
  <<: *default
  database: flash_cards_test

production:
  <<: *default
  database: flash_cards_production
  username: flash_cards_user
  password: <%= ENV['FLASH_CARDS_PASSWORD'] %>
